# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9dd205060d79da95acbdfa1115f2f53f4ed5032a94f8d3a47815725488248757ca0fff883ecceffd0b8f664e288878e9dedf5d6de3b8e0aa23f828b20417769
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
test:
  secret_key_base: ad6a757fdf3839299a1236e3b99026f90b2b4bbc4578a4e3129b599bb7fecdcc53cae7b2cbf17eed3b78341b1d57b05efa8e7ddd38c1c82edb7914ed773e2ef8
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
